/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddPlaceRouteImport } from './routes/add-place'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlacesIdRouteImport } from './routes/places.$id'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPlaceRoute = AddPlaceRouteImport.update({
  id: '/add-place',
  path: '/add-place',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesIdRoute = PlacesIdRouteImport.update({
  id: '/places/$id',
  path: '/places/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-place': typeof AddPlaceRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/places/$id': typeof PlacesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-place': typeof AddPlaceRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/places/$id': typeof PlacesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-place': typeof AddPlaceRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/places/$id': typeof PlacesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-place'
    | '/admin'
    | '/auth'
    | '/favorites'
    | '/search'
    | '/categories/$slug'
    | '/places/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-place'
    | '/admin'
    | '/auth'
    | '/favorites'
    | '/search'
    | '/categories/$slug'
    | '/places/$id'
  id:
    | '__root__'
    | '/'
    | '/add-place'
    | '/admin'
    | '/auth'
    | '/favorites'
    | '/search'
    | '/categories/$slug'
    | '/places/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddPlaceRoute: typeof AddPlaceRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  FavoritesRoute: typeof FavoritesRoute
  SearchRoute: typeof SearchRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  PlacesIdRoute: typeof PlacesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-place': {
      id: '/add-place'
      path: '/add-place'
      fullPath: '/add-place'
      preLoaderRoute: typeof AddPlaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$id': {
      id: '/places/$id'
      path: '/places/$id'
      fullPath: '/places/$id'
      preLoaderRoute: typeof PlacesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddPlaceRoute: AddPlaceRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  FavoritesRoute: FavoritesRoute,
  SearchRoute: SearchRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  PlacesIdRoute: PlacesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
