/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddPlaceRouteImport } from './routes/add-place'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PlacesIdRouteImport } from './routes/places.$id'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPlacesRouteImport } from './routes/admin.places'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminPlacesNewRouteImport } from './routes/admin.places.new'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPlaceRoute = AddPlaceRouteImport.update({
  id: '/add-place',
  path: '/add-place',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PlacesIdRoute = PlacesIdRouteImport.update({
  id: '/places/$id',
  path: '/places/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlacesRoute = AdminPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlacesNewRoute = AdminPlacesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPlacesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-place': typeof AddPlaceRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/places': typeof AdminPlacesRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/places/$id': typeof PlacesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/places/new': typeof AdminPlacesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-place': typeof AddPlaceRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/places': typeof AdminPlacesRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/places/$id': typeof PlacesIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/places/new': typeof AdminPlacesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-place': typeof AddPlaceRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/places': typeof AdminPlacesRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/places/$id': typeof PlacesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/places/new': typeof AdminPlacesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-place'
    | '/admin'
    | '/auth'
    | '/favorites'
    | '/search'
    | '/admin/categories'
    | '/admin/locations'
    | '/admin/places'
    | '/admin/products'
    | '/categories/$slug'
    | '/places/$id'
    | '/admin/'
    | '/admin/places/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-place'
    | '/auth'
    | '/favorites'
    | '/search'
    | '/admin/categories'
    | '/admin/locations'
    | '/admin/places'
    | '/admin/products'
    | '/categories/$slug'
    | '/places/$id'
    | '/admin'
    | '/admin/places/new'
  id:
    | '__root__'
    | '/'
    | '/add-place'
    | '/admin'
    | '/auth'
    | '/favorites'
    | '/search'
    | '/admin/categories'
    | '/admin/locations'
    | '/admin/places'
    | '/admin/products'
    | '/categories/$slug'
    | '/places/$id'
    | '/admin/'
    | '/admin/places/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddPlaceRoute: typeof AddPlaceRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  FavoritesRoute: typeof FavoritesRoute
  SearchRoute: typeof SearchRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  PlacesIdRoute: typeof PlacesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-place': {
      id: '/add-place'
      path: '/add-place'
      fullPath: '/add-place'
      preLoaderRoute: typeof AddPlaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/places/$id': {
      id: '/places/$id'
      path: '/places/$id'
      fullPath: '/places/$id'
      preLoaderRoute: typeof PlacesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/places': {
      id: '/admin/places'
      path: '/places'
      fullPath: '/admin/places'
      preLoaderRoute: typeof AdminPlacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/places/new': {
      id: '/admin/places/new'
      path: '/new'
      fullPath: '/admin/places/new'
      preLoaderRoute: typeof AdminPlacesNewRouteImport
      parentRoute: typeof AdminPlacesRoute
    }
  }
}

interface AdminPlacesRouteChildren {
  AdminPlacesNewRoute: typeof AdminPlacesNewRoute
}

const AdminPlacesRouteChildren: AdminPlacesRouteChildren = {
  AdminPlacesNewRoute: AdminPlacesNewRoute,
}

const AdminPlacesRouteWithChildren = AdminPlacesRoute._addFileChildren(
  AdminPlacesRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminPlacesRoute: typeof AdminPlacesRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminPlacesRoute: AdminPlacesRouteWithChildren,
  AdminProductsRoute: AdminProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddPlaceRoute: AddPlaceRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  FavoritesRoute: FavoritesRoute,
  SearchRoute: SearchRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  PlacesIdRoute: PlacesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
